--------------------------------------------------------
--  파일이 생성됨 - 월요일-12월-20-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TODO
--------------------------------------------------------

  CREATE TABLE "HR"."TODO" 
   (	"TODO_ID" NUMBER(6,0), 
	"TODO_CONTENTS" VARCHAR2(1000 BYTE), 
	"TODO_DEADLINE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TODO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."TODO_PK" ON "HR"."TODO" ("TODO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TODO
--------------------------------------------------------

  ALTER TABLE "HR"."TODO" MODIFY ("TODO_DEADLINE" NOT NULL ENABLE);
  ALTER TABLE "HR"."TODO" ADD CONSTRAINT "TODO_PK" PRIMARY KEY ("TODO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."TODO" MODIFY ("TODO_ID" NOT NULL ENABLE);
