--------------------------------------------------------
--  파일이 생성됨 - 목요일-12월-16-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CARD
--------------------------------------------------------

  CREATE TABLE "HR"."CARD" 
   (	"CARD_NUM" NUMBER(6,0), 
	"PRICE" NUMBER(6,0), 
	"CUSTOMER_ID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "HR"."CUSTOMER" 
   (	"CUSTOMER_ID" NUMBER(6,0), 
	"CUSTOMER_NAME" VARCHAR2(20 BYTE), 
	"CUSTOMER_PWD" VARCHAR2(20 BYTE), 
	"SHOP_ID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER_INFO
--------------------------------------------------------

  CREATE TABLE "HR"."CUSTOMER_INFO" 
   (	"MEMBER_RANK" VARCHAR2(20 BYTE), 
	"STARCOUNT" NUMBER(6,0), 
	"CUSTOMER_ID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MANAGER
--------------------------------------------------------

  CREATE TABLE "HR"."MANAGER" 
   (	"MANAGER_ID" NUMBER(6,0), 
	"MANAGER_NAME" VARCHAR2(20 BYTE), 
	"MANAGER_PWD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "HR"."MENU" 
   (	"MENU_ID" NUMBER(6,0), 
	"MENU_CATEGORY" VARCHAR2(20 BYTE), 
	"MENU_NAME" VARCHAR2(20 BYTE), 
	"MENU_PRICE" NUMBER(6,0), 
	"SHOP_ID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAYMENT
--------------------------------------------------------

  CREATE TABLE "HR"."PAYMENT" 
   (	"PAY_DAY" DATE, 
	"SHOP_ID" NUMBER(6,0), 
	"MENU_ID" NUMBER(6,0), 
	"MENU_PRICE" NUMBER(6,0), 
	"CUSTOMER_ID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SHOP
--------------------------------------------------------

  CREATE TABLE "HR"."SHOP" 
   (	"SHOP_ID" NUMBER(6,0), 
	"SHOP_NAME" VARCHAR2(30 BYTE), 
	"SHOP_LOCATION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."CARD_PK" ON "HR"."CARD" ("CARD_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."CUSTOMER_PK" ON "HR"."CUSTOMER" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MANAGER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."MANAGER_PK" ON "HR"."MANAGER" ("MANAGER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."MENU_PK" ON "HR"."MENU" ("MENU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MENU_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."MENU_UK1" ON "HR"."MENU" ("MENU_PRICE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SHOP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SHOP_PK" ON "HR"."SHOP" ("SHOP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CARD
--------------------------------------------------------

  ALTER TABLE "HR"."CARD" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."CARD" ADD CONSTRAINT "CARD_PK" PRIMARY KEY ("CARD_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."CARD" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "HR"."CARD" MODIFY ("CARD_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "HR"."CUSTOMER" MODIFY ("SHOP_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."CUSTOMER" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."CUSTOMER" MODIFY ("CUSTOMER_PWD" NOT NULL ENABLE);
  ALTER TABLE "HR"."CUSTOMER" MODIFY ("CUSTOMER_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMER_INFO
--------------------------------------------------------

  ALTER TABLE "HR"."CUSTOMER_INFO" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."CUSTOMER_INFO" MODIFY ("MEMBER_RANK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MANAGER
--------------------------------------------------------

  ALTER TABLE "HR"."MANAGER" ADD CONSTRAINT "MANAGER_PK" PRIMARY KEY ("MANAGER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."MANAGER" MODIFY ("MANAGER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "HR"."MENU" ADD CONSTRAINT "MENU_UK1" UNIQUE ("MENU_PRICE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."MENU" MODIFY ("SHOP_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."MENU" ADD CONSTRAINT "MENU_PK" PRIMARY KEY ("MENU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."MENU" MODIFY ("MENU_PRICE" NOT NULL ENABLE);
  ALTER TABLE "HR"."MENU" MODIFY ("MENU_NAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."MENU" MODIFY ("MENU_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "HR"."MENU" MODIFY ("MENU_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "HR"."PAYMENT" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."PAYMENT" MODIFY ("MENU_PRICE" NOT NULL ENABLE);
  ALTER TABLE "HR"."PAYMENT" MODIFY ("MENU_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."PAYMENT" MODIFY ("SHOP_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."PAYMENT" MODIFY ("PAY_DAY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SHOP
--------------------------------------------------------

  ALTER TABLE "HR"."SHOP" MODIFY ("SHOP_LOCATION" NOT NULL ENABLE);
  ALTER TABLE "HR"."SHOP" MODIFY ("SHOP_NAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."SHOP" ADD CONSTRAINT "SHOP_PK" PRIMARY KEY ("SHOP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."SHOP" MODIFY ("SHOP_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CARD
--------------------------------------------------------

  ALTER TABLE "HR"."CARD" ADD CONSTRAINT "CARD_CUSTOMER_ID_FK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "HR"."CUSTOMER" ("CUSTOMER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "HR"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_SHOP_ID_FK" FOREIGN KEY ("SHOP_ID")
	  REFERENCES "HR"."SHOP" ("SHOP_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUSTOMER_INFO
--------------------------------------------------------

  ALTER TABLE "HR"."CUSTOMER_INFO" ADD CONSTRAINT "CUSTOMER_INFO_CUSTOMER_ID_FK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "HR"."CUSTOMER" ("CUSTOMER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "HR"."MENU" ADD CONSTRAINT "MENU_SHOP_ID_FK" FOREIGN KEY ("SHOP_ID")
	  REFERENCES "HR"."SHOP" ("SHOP_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "HR"."PAYMENT" ADD CONSTRAINT "PAYMENT_CUSTOMER_ID_FK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "HR"."CUSTOMER" ("CUSTOMER_ID") ENABLE;
  ALTER TABLE "HR"."PAYMENT" ADD CONSTRAINT "PAYMENT_MENU_ID_FK" FOREIGN KEY ("MENU_ID")
	  REFERENCES "HR"."MENU" ("MENU_ID") ENABLE;
  ALTER TABLE "HR"."PAYMENT" ADD CONSTRAINT "PAYMENT_MENU_PRICE_FK" FOREIGN KEY ("MENU_PRICE")
	  REFERENCES "HR"."MENU" ("MENU_PRICE") ENABLE;
  ALTER TABLE "HR"."PAYMENT" ADD CONSTRAINT "PAYMENT_SHOP_ID_FK" FOREIGN KEY ("SHOP_ID")
	  REFERENCES "HR"."SHOP" ("SHOP_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SHOP
--------------------------------------------------------

  ALTER TABLE "HR"."SHOP" ADD FOREIGN KEY ("SHOP_ID")
	  REFERENCES "HR"."CUSTOMER" ("CUSTOMER_ID") ENABLE;
